_dim_ = 256
_ffn_dim_ = 512
_num_levels_ = 4
_pos_dim_ = 128
agent_fut_steps = 6
bev_h_ = 200
bev_w_ = 200
cameras = [
    'CAM_BACK',
    'CAM_BACK_LEFT',
    'CAM_BACK_RIGHT',
    'CAM_FRONT',
    'CAM_FRONT_LEFT',
    'CAM_FRONT_RIGHT',
]
class_names = [
    'car',
    'truck',
    'construction_vehicle',
    'bus',
    'trailer',
    'barrier',
    'motorcycle',
    'bicycle',
    'pedestrian',
    'traffic_cone',
]
data_prefix = dict(
    CAM_BACK='samples/CAM_BACK',
    CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
    CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
    CAM_FRONT='samples/CAM_FRONT',
    CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
    CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
    img='',
    pts='samples/LIDAR_TOP',
    sweeps='sweeps/LIDAR_TOP')
data_root = 'data/nuscenes/'
dataset_type = 'NuScenesDatasetVAD'
default_hooks = dict(
    checkpoint=dict(
        by_epoch=True,
        interval=1,
        max_keep_ckpts=3,
        save_begin=0,
        save_best='auto',
        type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    timer=dict(type='IterTimerHook'))
default_scope = 'fsd'
ego_fut_steps = 6
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
evaluation = dict(
    interval=1,
    pipeline=[
        dict(
            _scope_='mmdet3d',
            num_views=6,
            to_float32=True,
            type='LoadMultiViewImageFromFiles'),
        dict(
            type='LoadAnnotationsPlan3D',
            with_bbox_3d=True,
            with_instances_ids=True,
            with_instances_traj=True,
            with_label_3d=True,
            with_vector_map=True),
        dict(
            point_cloud_range=[
                -15.0,
                -30.0,
                -2.0,
                15.0,
                30.0,
                2.0,
            ],
            type='ObjectRangeFilter'),
        dict(
            classes=[
                'car',
                'truck',
                'construction_vehicle',
                'bus',
                'trailer',
                'barrier',
                'motorcycle',
                'bicycle',
                'pedestrian',
                'traffic_cone',
            ],
            type='ObjectNameFilter'),
        dict(
            divider=1.0,
            mean=[
                123.675,
                116.28,
                103.53,
            ],
            std=[
                58.395,
                57.12,
                57.375,
            ],
            to_rgb=True,
            type='NormalizeMultiviewImage'),
        dict(scales=[
            0.8,
        ], type='RandomScaleImageMultiViewImage'),
        dict(size_divisor=32, type='PadMultiViewImage'),
        dict(
            keys=[
                'img',
                'gt_bboxes_3d',
                'gt_labels_3d',
                'gt_bboxes_traj',
                'gt_bboxes_traj_mask',
                'bboxes_context',
                'gt_ego_traj',
                'gt_ego_traj_mask',
                'ego_command',
                'ego_context',
                'ego_history_traj',
                'ego_history_mask',
                'gt_map_vectors_pt',
                'gt_map_vectors_label',
            ],
            type='Pack3DPlanInputs'),
    ])
file_client_args = dict(backend='disk')
img_norm_cfg = dict(
    mean=[
        123.675,
        116.28,
        103.53,
    ],
    std=[
        58.395,
        57.12,
        57.375,
    ],
    to_rgb=True)
input_modality = dict(
    use_camera=True,
    use_external=True,
    use_lidar=False,
    use_map=False,
    use_radar=False)
load_from = './ckpts/vad_base.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
lr_config = dict(
    min_lr_ratio=0.001,
    policy='CosineAnnealing',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333)
map_classes = [
    'divider',
    'ped_crossing',
    'boundary',
]
map_eval_use_same_gt_sample_num_flag = True
map_fixed_ptsnum_per_gt_line = 20
map_fixed_ptsnum_per_pred_line = 20
map_num_classes = 3
map_num_vec = 100
metainfo = dict(
    classes=[
        'car',
        'truck',
        'construction_vehicle',
        'bus',
        'trailer',
        'barrier',
        'motorcycle',
        'bicycle',
        'pedestrian',
        'traffic_cone',
    ],
    map_classes=[
        'divider',
        'ped_crossing',
        'boundary',
    ],
    version='v1.0-mini')
model = dict(
    img_backbone=dict(
        _scope_='mmdet',
        depth=50,
        frozen_stages=1,
        init_cfg=dict(checkpoint='torchvision://resnet50', type='Pretrained'),
        norm_cfg=dict(requires_grad=False, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            1,
            2,
            3,
        ),
        style='pytorch',
        type='ResNet'),
    img_neck=dict(
        _scope_='mmdet',
        add_extra_convs='on_output',
        in_channels=[
            512,
            1024,
            2048,
        ],
        num_outs=4,
        out_channels=256,
        relu_before_extra_convs=True,
        start_level=0,
        type='FPN'),
    pts_bbox_head=dict(
        as_two_stage=False,
        bbox_coder=dict(
            max_num=100,
            num_classes=10,
            pc_range=[
                -15.0,
                -30.0,
                -2.0,
                15.0,
                30.0,
                2.0,
            ],
            post_center_range=[
                -20,
                -35,
                -10.0,
                20,
                35,
                10.0,
            ],
            type='CustomNMSFreeCoder',
            voxel_size=[
                0.15,
                0.15,
                4,
            ]),
        bev_h=200,
        bev_w=200,
        dis_thresh=0.2,
        ego_agent_decoder=dict(
            num_layers=1,
            return_intermediate=False,
            transformerlayers=dict(
                attn_cfgs=[
                    dict(
                        dropout=0.1,
                        embed_dims=256,
                        num_heads=8,
                        type='MultiheadAttention'),
                ],
                feedforward_channels=512,
                ffn_dropout=0.1,
                operation_order=(
                    'cross_attn',
                    'norm',
                    'ffn',
                    'norm',
                ),
                type='BaseTransformerLayer'),
            type='CustomTransformerDecoder'),
        ego_his_encoder=None,
        ego_lcf_feat_idx=None,
        ego_map_decoder=dict(
            num_layers=1,
            return_intermediate=False,
            transformerlayers=dict(
                attn_cfgs=[
                    dict(
                        dropout=0.1,
                        embed_dims=256,
                        num_heads=8,
                        type='MultiheadAttention'),
                ],
                feedforward_channels=512,
                ffn_dropout=0.1,
                operation_order=(
                    'cross_attn',
                    'norm',
                    'ffn',
                    'norm',
                ),
                type='BaseTransformerLayer'),
            type='CustomTransformerDecoder'),
        embed_dims=256,
        loss_bbox=dict(_scope_='mmdet', loss_weight=0.25, type='L1Loss'),
        loss_cls=dict(
            _scope_='mmdet',
            alpha=0.25,
            gamma=2.0,
            loss_weight=2.0,
            type='FocalLoss',
            use_sigmoid=True),
        loss_iou=dict(_scope_='mmdet', loss_weight=0.0, type='GIoULoss'),
        loss_map_bbox=dict(_scope_='mmdet', loss_weight=0.0, type='L1Loss'),
        loss_map_cls=dict(
            _scope_='mmdet',
            alpha=0.25,
            gamma=2.0,
            loss_weight=2.0,
            type='FocalLoss',
            use_sigmoid=True),
        loss_map_dir=dict(loss_weight=0.005, type='PtsDirCosLoss'),
        loss_map_iou=dict(_scope_='mmdet', loss_weight=0.0, type='GIoULoss'),
        loss_map_pts=dict(loss_weight=1.0, type='PtsL1Loss'),
        loss_plan_bound=dict(
            dis_thresh=1.0, loss_weight=1.0, type='PlanMapBoundLoss'),
        loss_plan_col=dict(loss_weight=1.0, type='PlanCollisionLoss'),
        loss_plan_dir=dict(loss_weight=0.5, type='PlanMapDirectionLoss'),
        loss_plan_reg=dict(_scope_='mmdet', loss_weight=1.0, type='L1Loss'),
        loss_traj=dict(_scope_='mmdet', loss_weight=0.2, type='L1Loss'),
        loss_traj_cls=dict(
            _scope_='mmdet',
            alpha=0.25,
            gamma=2.0,
            loss_weight=0.2,
            type='FocalLoss',
            use_sigmoid=True),
        map_bbox_coder=dict(
            max_num=50,
            num_classes=3,
            pc_range=[
                -15.0,
                -30.0,
                -2.0,
                15.0,
                30.0,
                2.0,
            ],
            post_center_range=[
                -20,
                -35,
                -20,
                -35,
                20,
                35,
                20,
                35,
            ],
            type='MapNMSFreeCoder',
            voxel_size=[
                0.15,
                0.15,
                4,
            ]),
        map_code_size=2,
        map_code_weights=[
            1.0,
            1.0,
            1.0,
            1.0,
        ],
        map_dir_interval=1,
        map_gt_shift_pts_pattern='v2',
        map_num_classes=3,
        map_num_pts_per_gt_vec=20,
        map_num_pts_per_vec=20,
        map_num_vec=100,
        map_query_embed_type='instance_pts',
        map_thresh=0.5,
        map_transform_method='minmax',
        motion_decoder=dict(
            num_layers=1,
            return_intermediate=False,
            transformerlayers=dict(
                attn_cfgs=[
                    dict(
                        dropout=0.1,
                        embed_dims=256,
                        num_heads=8,
                        type='MultiheadAttention'),
                ],
                feedforward_channels=512,
                ffn_dropout=0.1,
                operation_order=(
                    'cross_attn',
                    'norm',
                    'ffn',
                    'norm',
                ),
                type='BaseTransformerLayer'),
            type='CustomTransformerDecoder'),
        motion_map_decoder=dict(
            num_layers=1,
            return_intermediate=False,
            transformerlayers=dict(
                attn_cfgs=[
                    dict(
                        dropout=0.1,
                        embed_dims=256,
                        num_heads=8,
                        type='MultiheadAttention'),
                ],
                feedforward_channels=512,
                ffn_dropout=0.1,
                operation_order=(
                    'cross_attn',
                    'norm',
                    'ffn',
                    'norm',
                ),
                type='BaseTransformerLayer'),
            type='CustomTransformerDecoder'),
        num_classes=10,
        num_query=300,
        pe_normalization=True,
        positional_encoding=dict(
            _scope_='mmdet',
            col_num_embed=200,
            num_feats=128,
            row_num_embed=200,
            type='LearnedPositionalEncoding'),
        query_thresh=0.0,
        query_use_fix_pad=False,
        sync_cls_avg_factor=True,
        tot_epoch=60,
        train_cfg=dict(
            assigner=dict(
                cls_cost=dict(
                    _scope_='mmdet', type='FocalLossCost', weight=2.0),
                iou_cost=dict(_scope_='mmdet', type='IoUCost', weight=0.0),
                pc_range=[
                    -15.0,
                    -30.0,
                    -2.0,
                    15.0,
                    30.0,
                    2.0,
                ],
                reg_cost=dict(type='BBox3DL1Cost', weight=0.25),
                type='HungarianAssigner3D'),
            map_assigner=dict(
                cls_cost=dict(
                    _scope_='mmdet', type='FocalLossCost', weight=2.0),
                iou_cost=dict(iou_mode='giou', type='IoUCost', weight=0.0),
                pc_range=[
                    -15.0,
                    -30.0,
                    -2.0,
                    15.0,
                    30.0,
                    2.0,
                ],
                pts_cost=dict(type='OrderedPtsL1Cost', weight=1.0),
                reg_cost=dict(
                    box_format='xywh', type='BBoxL1Cost', weight=0.0),
                type='MapHungarianAssigner3D')),
        transformer=dict(
            decoder=dict(
                num_layers=6,
                return_intermediate=True,
                transformerlayers=dict(
                    _scope_='mmdet',
                    attn_cfgs=[
                        dict(
                            dropout=0.1,
                            embed_dims=256,
                            num_heads=8,
                            type='MultiheadAttention'),
                        dict(
                            _scope_='fsd',
                            embed_dims=256,
                            num_levels=1,
                            type='BEVMultiScaleDeformableAttention'),
                    ],
                    batch_first=False,
                    ffn_cfgs=dict(
                        act_cfg=dict(inplace=True, type='ReLU'),
                        embed_dims=256,
                        feedforward_channels=512,
                        ffn_drop=0.1,
                        num_fcs=2,
                        type='FFN'),
                    norm_cfg=dict(type='LN'),
                    operation_order=(
                        'self_attn',
                        'norm',
                        'cross_attn',
                        'norm',
                        'ffn',
                        'norm',
                    ),
                    type='BaseTransformerLayer'),
                type='DetectionTransformerDecoder'),
            embed_dims=256,
            encoder=dict(
                num_layers=6,
                num_points_in_pillar=4,
                pc_range=[
                    -15.0,
                    -30.0,
                    -2.0,
                    15.0,
                    30.0,
                    2.0,
                ],
                return_intermediate=False,
                transformerlayers=dict(
                    attn_cfgs=[
                        dict(
                            embed_dims=256,
                            num_levels=1,
                            type='TemporalSelfAttention'),
                        dict(
                            deformable_attention=dict(
                                embed_dims=256,
                                num_levels=4,
                                num_points=8,
                                type='MultiScaleDeformableAttention3D'),
                            embed_dims=256,
                            pc_range=[
                                -15.0,
                                -30.0,
                                -2.0,
                                15.0,
                                30.0,
                                2.0,
                            ],
                            type='SpatialCrossAttention'),
                    ],
                    feedforward_channels=512,
                    ffn_dropout=0.1,
                    operation_order=(
                        'self_attn',
                        'norm',
                        'cross_attn',
                        'norm',
                        'ffn',
                        'norm',
                    ),
                    type='BEVFormerLayer'),
                type='BEVFormerEncoder'),
            map_decoder=dict(
                num_layers=6,
                return_intermediate=True,
                transformerlayers=dict(
                    _scope_='mmdet',
                    attn_cfgs=[
                        dict(
                            dropout=0.1,
                            embed_dims=256,
                            num_heads=8,
                            type='MultiheadAttention'),
                        dict(
                            _scope_='fsd',
                            embed_dims=256,
                            num_levels=1,
                            type='BEVMultiScaleDeformableAttention'),
                    ],
                    batch_first=False,
                    ffn_cfgs=dict(
                        act_cfg=dict(inplace=True, type='ReLU'),
                        embed_dims=256,
                        feedforward_channels=512,
                        ffn_drop=0.1,
                        num_fcs=2,
                        type='FFN'),
                    norm_cfg=dict(type='LN'),
                    operation_order=(
                        'self_attn',
                        'norm',
                        'cross_attn',
                        'norm',
                        'ffn',
                        'norm',
                    ),
                    type='BaseTransformerLayer'),
                type='MapDetectionTransformerDecoder'),
            map_num_pts_per_vec=20,
            map_num_vec=100,
            rotate_prev_bev=True,
            type='VADPerceptionTransformer',
            use_can_bus=True,
            use_shift=True),
        type='VADHead',
        use_pe=True,
        use_traj_lr_warmup=False,
        valid_fut_ts=6,
        with_box_refine=True),
    train_cfg=dict(
        pts=dict(
            grid_size=[
                512,
                512,
                1,
            ],
            out_size_factor=4,
            point_cloud_range=[
                -15.0,
                -30.0,
                -2.0,
                15.0,
                30.0,
                2.0,
            ],
            voxel_size=[
                0.15,
                0.15,
                4,
            ])),
    type='VAD',
    use_grid_mask=True,
    video_test_mode=True)
num_classes = 10
optim_wrapper = dict(
    _scope_='mmdet',
    clip_grad=dict(max_norm=35, norm_type=2),
    optimizer=dict(lr=0.0002, type='AdamW', weight_decay=0.01),
    paramwise_cfg=dict(custom_keys=dict(img_backbone=dict(lr_mult=0.1))),
    type='OptimWrapper')
optimizer = dict(lr=0.0002, type='AdamW', weight_decay=0.01)
paramwise_cfg = dict(custom_keys=dict(img_backbone=dict(lr_mult=0.1)))
past_steps = 2
plugin = False
plugin_dir = 'fsd'
point_cloud_range = [
    -15.0,
    -30.0,
    -2.0,
    15.0,
    30.0,
    2.0,
]
queue_length = 4
randomness = dict(seed=2024)
resume = False
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='nuscenes_infos_val.pkl',
        bev_queue_length=4,
        bev_size=(
            200,
            200,
        ),
        box_type_3d='LiDAR',
        box_type_3d_original='LiDAR',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
            CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
            CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
            img='',
            pts='samples/LIDAR_TOP',
            sweeps='sweeps/LIDAR_TOP'),
        data_root='data/nuscenes/',
        map_fixed_ptsnum_per_line=20,
        map_sample_dist=1.0,
        map_sample_nums=250,
        metainfo=dict(
            classes=[
                'car',
                'truck',
                'construction_vehicle',
                'bus',
                'trailer',
                'barrier',
                'motorcycle',
                'bicycle',
                'pedestrian',
                'traffic_cone',
            ],
            map_classes=[
                'divider',
                'ped_crossing',
                'boundary',
            ],
            version='v1.0-mini'),
        modality=dict(
            use_camera=True,
            use_external=True,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        past_steps=2,
        pipeline=[
            dict(
                _scope_='mmdet3d',
                num_views=6,
                to_float32=True,
                type='LoadMultiViewImageFromFiles'),
            dict(
                type='LoadAnnotationsPlan3D',
                with_bbox_3d=True,
                with_instances_ids=True,
                with_instances_traj=True,
                with_label_3d=True,
                with_vector_map=True),
            dict(
                point_cloud_range=[
                    -15.0,
                    -30.0,
                    -2.0,
                    15.0,
                    30.0,
                    2.0,
                ],
                type='ObjectRangeFilter'),
            dict(
                classes=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                type='ObjectNameFilter'),
            dict(
                divider=1.0,
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                to_rgb=True,
                type='NormalizeMultiviewImage'),
            dict(scales=[
                0.8,
            ], type='RandomScaleImageMultiViewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                keys=[
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_bboxes_traj',
                    'gt_bboxes_traj_mask',
                    'bboxes_context',
                    'gt_ego_traj',
                    'gt_ego_traj_mask',
                    'ego_command',
                    'ego_context',
                    'ego_history_traj',
                    'ego_history_mask',
                    'gt_map_vectors_pt',
                    'gt_map_vectors_label',
                ],
                type='Pack3DPlanInputs'),
        ],
        planning_steps=6,
        point_cloud_range=[
            -15.0,
            -30.0,
            -2.0,
            15.0,
            30.0,
            2.0,
        ],
        prediction_steps=6,
        test_mode=True,
        type='NuScenesDatasetVAD',
        with_can_bus=True),
    num_workers=4,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(_scope_='mmengine', shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    _scope_='mmdet3d',
    ann_file='data/nuscenes//nuscenes_infos_val.pkl',
    data_root='data/nuscenes/',
    jsonfile_prefix='eval',
    metric='bbox',
    modality=dict(
        use_camera=True,
        use_external=True,
        use_lidar=False,
        use_map=False,
        use_radar=False),
    type='NuScenesMetric')
test_pipeline = [
    dict(
        _scope_='mmdet3d',
        num_views=6,
        to_float32=True,
        type='LoadMultiViewImageFromFiles'),
    dict(
        type='LoadAnnotationsPlan3D',
        with_bbox_3d=True,
        with_instances_ids=True,
        with_instances_traj=True,
        with_label_3d=True,
        with_vector_map=True),
    dict(
        point_cloud_range=[
            -15.0,
            -30.0,
            -2.0,
            15.0,
            30.0,
            2.0,
        ],
        type='ObjectRangeFilter'),
    dict(
        classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ],
        type='ObjectNameFilter'),
    dict(
        divider=1.0,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        to_rgb=True,
        type='NormalizeMultiviewImage'),
    dict(scales=[
        0.8,
    ], type='RandomScaleImageMultiViewImage'),
    dict(size_divisor=32, type='PadMultiViewImage'),
    dict(
        keys=[
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_bboxes_traj',
            'gt_bboxes_traj_mask',
            'bboxes_context',
            'gt_ego_traj',
            'gt_ego_traj_mask',
            'ego_command',
            'ego_context',
            'ego_history_traj',
            'ego_history_mask',
            'gt_map_vectors_pt',
            'gt_map_vectors_label',
        ],
        type='Pack3DPlanInputs'),
]
total_epochs = 60
train_cfg = dict(max_epochs=60, type='EpochBasedTrainLoop', val_interval=1)
train_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='nuscenes_infos_train.pkl',
        bev_queue_length=4,
        bev_size=(
            200,
            200,
        ),
        box_type_3d='LiDAR',
        box_type_3d_original='LiDAR',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
            CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
            CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
            img='',
            pts='samples/LIDAR_TOP',
            sweeps='sweeps/LIDAR_TOP'),
        data_root='data/nuscenes/',
        map_fixed_ptsnum_per_line=20,
        map_sample_dist=1.0,
        map_sample_nums=250,
        metainfo=dict(
            classes=[
                'car',
                'truck',
                'construction_vehicle',
                'bus',
                'trailer',
                'barrier',
                'motorcycle',
                'bicycle',
                'pedestrian',
                'traffic_cone',
            ],
            map_classes=[
                'divider',
                'ped_crossing',
                'boundary',
            ],
            version='v1.0-mini'),
        modality=dict(
            use_camera=True,
            use_external=True,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        past_steps=2,
        pipeline=[
            dict(
                _scope_='mmdet3d',
                num_views=6,
                to_float32=True,
                type='LoadMultiViewImageFromFiles'),
            dict(type='PhotoMetricDistortionMultiViewImage'),
            dict(
                type='LoadAnnotationsPlan3D',
                with_bbox_3d=True,
                with_instances_ids=True,
                with_instances_traj=True,
                with_label_3d=True,
                with_vector_map=True),
            dict(
                point_cloud_range=[
                    -15.0,
                    -30.0,
                    -2.0,
                    15.0,
                    30.0,
                    2.0,
                ],
                type='ObjectRangeFilter'),
            dict(
                classes=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                type='ObjectNameFilter'),
            dict(
                divider=1.0,
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                to_rgb=True,
                type='NormalizeMultiviewImage'),
            dict(scales=[
                0.8,
            ], type='RandomScaleImageMultiViewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                keys=[
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_bboxes_traj',
                    'gt_bboxes_traj_mask',
                    'bboxes_context',
                    'gt_ego_traj',
                    'gt_ego_traj_mask',
                    'ego_command',
                    'ego_context',
                    'ego_history_traj',
                    'ego_history_mask',
                    'gt_map_vectors_pt',
                    'gt_map_vectors_label',
                ],
                type='Pack3DPlanInputs'),
        ],
        planning_steps=6,
        point_cloud_range=[
            -15.0,
            -30.0,
            -2.0,
            15.0,
            30.0,
            2.0,
        ],
        prediction_steps=6,
        test_mode=False,
        type='NuScenesDatasetVAD',
        with_can_bus=True),
    num_workers=4,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(_scope_='mmengine', shuffle=False, type='DefaultSampler'))
train_pipeline = [
    dict(
        _scope_='mmdet3d',
        num_views=6,
        to_float32=True,
        type='LoadMultiViewImageFromFiles'),
    dict(type='PhotoMetricDistortionMultiViewImage'),
    dict(
        type='LoadAnnotationsPlan3D',
        with_bbox_3d=True,
        with_instances_ids=True,
        with_instances_traj=True,
        with_label_3d=True,
        with_vector_map=True),
    dict(
        point_cloud_range=[
            -15.0,
            -30.0,
            -2.0,
            15.0,
            30.0,
            2.0,
        ],
        type='ObjectRangeFilter'),
    dict(
        classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ],
        type='ObjectNameFilter'),
    dict(
        divider=1.0,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        to_rgb=True,
        type='NormalizeMultiviewImage'),
    dict(scales=[
        0.8,
    ], type='RandomScaleImageMultiViewImage'),
    dict(size_divisor=32, type='PadMultiViewImage'),
    dict(
        keys=[
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_bboxes_traj',
            'gt_bboxes_traj_mask',
            'bboxes_context',
            'gt_ego_traj',
            'gt_ego_traj_mask',
            'ego_command',
            'ego_context',
            'ego_history_traj',
            'ego_history_mask',
            'gt_map_vectors_pt',
            'gt_map_vectors_label',
        ],
        type='Pack3DPlanInputs'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='nuscenes_infos_val.pkl',
        bev_queue_length=4,
        bev_size=(
            200,
            200,
        ),
        box_type_3d='LiDAR',
        box_type_3d_original='LiDAR',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
            CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
            CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
            img='',
            pts='samples/LIDAR_TOP',
            sweeps='sweeps/LIDAR_TOP'),
        data_root='data/nuscenes/',
        map_fixed_ptsnum_per_line=20,
        map_sample_dist=1.0,
        map_sample_nums=250,
        metainfo=dict(
            classes=[
                'car',
                'truck',
                'construction_vehicle',
                'bus',
                'trailer',
                'barrier',
                'motorcycle',
                'bicycle',
                'pedestrian',
                'traffic_cone',
            ],
            map_classes=[
                'divider',
                'ped_crossing',
                'boundary',
            ],
            version='v1.0-mini'),
        modality=dict(
            use_camera=True,
            use_external=True,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        past_steps=2,
        pipeline=[
            dict(
                _scope_='mmdet3d',
                num_views=6,
                to_float32=True,
                type='LoadMultiViewImageFromFiles'),
            dict(
                type='LoadAnnotationsPlan3D',
                with_bbox_3d=True,
                with_instances_ids=True,
                with_instances_traj=True,
                with_label_3d=True,
                with_vector_map=True),
            dict(
                point_cloud_range=[
                    -15.0,
                    -30.0,
                    -2.0,
                    15.0,
                    30.0,
                    2.0,
                ],
                type='ObjectRangeFilter'),
            dict(
                classes=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                type='ObjectNameFilter'),
            dict(
                divider=1.0,
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                to_rgb=True,
                type='NormalizeMultiviewImage'),
            dict(scales=[
                0.8,
            ], type='RandomScaleImageMultiViewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                keys=[
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'gt_bboxes_traj',
                    'gt_bboxes_traj_mask',
                    'bboxes_context',
                    'gt_ego_traj',
                    'gt_ego_traj_mask',
                    'ego_command',
                    'ego_context',
                    'ego_history_traj',
                    'ego_history_mask',
                    'gt_map_vectors_pt',
                    'gt_map_vectors_label',
                ],
                type='Pack3DPlanInputs'),
        ],
        planning_steps=6,
        point_cloud_range=[
            -15.0,
            -30.0,
            -2.0,
            15.0,
            30.0,
            2.0,
        ],
        prediction_steps=6,
        test_mode=True,
        type='NuScenesDatasetVAD',
        with_can_bus=True),
    num_workers=4,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(_scope_='mmengine', shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    _scope_='mmdet3d',
    ann_file='data/nuscenes//nuscenes_infos_val.pkl',
    data_root='data/nuscenes/',
    jsonfile_prefix='eval',
    metric='bbox',
    modality=dict(
        use_camera=True,
        use_external=True,
        use_lidar=False,
        use_map=False,
        use_radar=False),
    type='NuScenesMetric')
version = 'v1.0-mini'
vis_backends = [
    dict(type='TensorboardVisBackend'),
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='Visualizer',
    vis_backends=[
        dict(type='TensorboardVisBackend'),
        dict(type='LocalVisBackend'),
    ])
voxel_size = [
    0.15,
    0.15,
    4,
]
work_dir = '.'
